version: "3.3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=conggioi123
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    networks:
      - doanchuyennganh-network
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - doanchuyennganh-network
    ports:
      - "8080:15672"
      - "5672:5672"
  

      
networks:
  doanchuyennganh-network:
    driver: bridge