version: "3.4"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        networks:
            - doanchuyennganh-network
        restart: always
        environment:
            - NODE_ENV="development"

    nginx-backend:
        build:
            context: ./nginx
            dockerfile: Dockerfile.backend
        depends_on:
            - backend
        networks:
            - doanchuyennganh-network
        ports:
            - "80:80"
            - "443:443"
        command: nginx -g "daemon off;"

networks:
    doanchuyennganh-network:
        driver: bridge
