version: "3.3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=conggioi123
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    networks:
      - doanchuyennganh-network
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - doanchuyennganh-network
    ports:
      - "8080:15672"
      - "5672:5672"
    depends_on:
      - mongodb
      - kong-gateway
  kong-gateway:
    container_name: Kong-gateway
    image: kong/kong-gateway:3.5.0.2
    networks:
      - doanchuyennganh-network
    volumes:
      - ./KongGateway:/kong/declarative/
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
  sendmail-services:
    build: 
      context: ./Backend/SendMailService
      dockerfile: Dockerfile
    networks:
      - doanchuyennganh-network
    restart: always
    environment:
      - USER_EMAIL=conggioi.dev@gmail.com
      - PASSWORD=ebcxkhuuhuvgbdoj
      - PORT=587
      - RABBITMQ_URI=amqp://rabbitmq
      - SEND_TYPE=topic
      - EXCHANGE=send_mail
    depends_on:
      - rabbitmq
      
networks:
  doanchuyennganh-network:
    driver: bridge