import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["vietnamese"] });
import { StrictMode } from "react";
export const metadata: Metadata = {
    title: "Quản lý giao hàng",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <head>
                <title>Quản lý Giao Hàng</title>
            </head>
            <body
                className={`${inter.className}`}
                suppressHydrationWarning={true}
            >
                <StrictMode>{children}</StrictMode>
            </body>
        </html>
    );
}
