module.exports = {
    SECRET_KEY_SHIPPER: "SECRET-DO-AN-CHUYEN-NGANH-shipper",
    KEY_SHIPPER: "KEY-DO-AN-CHUYEN-NGANH-shipper",
    SECRET_KEY_SHOP_USER: "SECRET-DO-AN-CHUYEN-NGANH-shopuser",
    KEY_SHOP_USER: "KEY-DO-AN-CHUYEN-NGANH-shopuser",
    KEY : "KEY-DO-AN-CHUYEN-NGANH",
    SECRET : "SECRET-DO-AN-CHUYEN-NGANH",
    PORT : process.env.PORT || 3001
}